# Copyright (c) 2026 Props3D. SPDX-License-Identifier: MIT
"""Create the sample Input Mapping Context for Blamcon Lightguns, with mouse parity.

Unreal assets are binary and can only be written by the editor, so the sample is generated by this script
instead of being authored by hand. Run it once in the Unreal Editor, then commit the assets it creates:

    1. Enable the "Python Editor Script Plugin" for the project.
    2. Tools > Execute Python Script... and pick this file.

It creates, in the plugin's content (Content Browser: Plugins > Blamcon Lightguns Content > Samples):

    IA_LightgunAim    Axis2D   aim position, 0..1, Y = 0 at the bottom
    IA_LightgunFire   Digital
    IMC_Lightgun      Lightgun Aim           -> IA_LightgunAim
                      Mouse XY 2D-Axis       -> IA_LightgunAim   (Lightgun Mouse Aim modifier + trigger)
                      Lightgun Trigger       -> IA_LightgunFire
                      Left Mouse Button      -> IA_LightgunFire

Running it again rebuilds the mappings and leaves the actions' other settings alone.
"""

import unreal

SAMPLE_PATH = "/BlamconLightguns/Samples"


def make_key(name):
    key = unreal.Key()
    key.set_editor_property("key_name", name)
    return key


def load_or_create(name, asset_class, factory):
    path = "{}/{}".format(SAMPLE_PATH, name)
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        return unreal.EditorAssetLibrary.load_asset(path)
    asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, SAMPLE_PATH, asset_class, factory)
    if asset is None:
        raise RuntimeError("Could not create {}".format(path))
    return asset


def main():
    aim = load_or_create("IA_LightgunAim", unreal.InputAction, unreal.InputAction_Factory())
    aim.set_editor_property("value_type", unreal.InputActionValueType.AXIS2D)

    fire = load_or_create("IA_LightgunFire", unreal.InputAction, unreal.InputAction_Factory())
    fire.set_editor_property("value_type", unreal.InputActionValueType.BOOLEAN)

    context = load_or_create("IMC_Lightgun", unreal.InputMappingContext, unreal.InputMappingContext_Factory())
    context.set_editor_property("mappings", [])

    context.map_key(aim, make_key("Lightgun_Aim"))
    context.map_key(aim, make_key("Mouse2D"))
    context.map_key(fire, make_key("Lightgun_Trigger"))
    context.map_key(fire, make_key("LeftMouseButton"))

    # Mappings come back from Python as copies: edit the list, then write it back.
    mappings = context.get_editor_property("mappings")
    for mapping in mappings:
        if str(mapping.get_editor_property("key").get_editor_property("key_name")) == "Mouse2D":
            mapping.set_editor_property("modifiers", [unreal.new_object(unreal.LightgunMouseAimModifier, outer=context)])
            mapping.set_editor_property("triggers", [unreal.new_object(unreal.LightgunMouseAimTrigger, outer=context)])
    context.set_editor_property("mappings", mappings)

    for asset in (aim, fire, context):
        unreal.EditorAssetLibrary.save_loaded_asset(asset)

    unreal.log("Blamcon Lightguns: sample input assets written to {}".format(SAMPLE_PATH))


main()
